config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products, path: 'materiais' do
    get :add_quantity
    get :remove_quantity
  end
  resources :control_users, path: 'usuarios', only: %i[index new create edit update destroy]
  devise_for :users
  devise_scope :user do
    root to: 'products#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :product_logs

  def amount
    product_logs.sum(:quantity)
  end

  def add_quantity(user_id, quantity = 1)
    product_log = product_logs.build(user_id: user_id, quantity: quantity)
    product_log.save
  end

  def remove_quantity(user_id, quantity = -1)
    product_log = product_logs.build(user_id: user_id, quantity: quantity)
    product_log.save
  end
end

app/models/product_log.rb
# frozen_string_literal: true

class ProductLog < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def add?
    quantity > 0
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
  has_many :product_logs
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end
end

app/controllers/control_users_controller.rb
# frozen_string_literal: true

class ControlUsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to control_users_url, notice: 'O Usuário foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to (current_user.nil? ? new_user_session_path : control_users_url), notice: 'O Usuário foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[show edit update destroy add_quantity remove_quantity]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to edit_product_path(@product), notice: 'O Produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to edit_product_path(@product), notice: 'O Produto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'O Produto foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  def add_quantity
    @product.add_quantity(current_user.id)
    redirect_back(fallback_location: root_path, notice: 'Quantidade aumentada')
  end

  def remove_quantity
    if Time.now.during_business_hours?
      @product.remove_quantity(current_user.id)
      redirect_back(fallback_location: root_path, notice: 'Quantidade diminuída')
    else
      redirect_to root_path, notice: 'Fora do horário permitido'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id] || params[:product_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def can_add_product_log?(product)
    if product.new_record?
      false
    else
      true
    end
  end

  def can_remove_product_log?(product)
    if !Time.now.during_business_hours? || product.new_record?
      false
    else
      product.amount > 0
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/control_users/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_with(model: user, url: (user.new_record? ? control_users_path : control_user_path(user)), local: true) do |form| %>
      <% if user.errors.any? %>
        <div class="alert alert-danger">
          <h5><%= t('errors_on_save') %></h5>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control', placeholder: t('activerecord.attributes.user.name'), autofocus: true %>
        </div>
        <div class="form-group col-md-6">
          <%= form.label :email %>
          <%= form.email_field :email, class: 'form-control' %>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :password %>
          <%= form.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group col-md-6">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-12">
          <div class="btn-group pull-right">
            <%= link_to t('back'), control_users_path, class: 'btn btn-default' %>
            <%= form.submit class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/control_users/edit.html.erb
<h3 class="text-center"><%= t('navigation.users.edit', amount: @user.product_logs.count) %></h3>

<%= render 'form', user: @user %>
<%= render 'products/product_logs', product_logs: @user.product_logs %>

app/views/control_users/index.html.erb
<h3 class="text-center"><%= t('navigation.users.title') %></h3>
<table class="table mt-3 mb-3 datatable">
  <thead>
    <tr>
      <th data-data="name">Nome</th>
      <th data-data="email">E-mail</th>
      <th>Atividades em Produtos</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%=user.name%></td>
      <td><%=user.email%></td>
      <td><%=user.product_logs.count%></td>
      <td>
        <%= link_to 'Exibir Detalhes e Log de Alterações', edit_control_user_path(user), class: 'btn btn-sm btn-primary' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/control_users/new.html.erb
<h3 class="text-center">
	<%= t('navigation.users.new') %>
</h3>

<%= render 'form', user: @user %>

app/views/control_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/layouts/_footer.html.erb
<p class="text-muted text-center">Construído por <a href="mailto:rodrigo@rtoledo.inf.br" target="_blank">Rodrigo Toledo</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=t(:system_name)%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script> -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body class="<%=controller_name%>">
    <header role="banner">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collpase-1">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to t('navigation.root'), root_path, class: 'navbar-brand' %>
          </div>
          <div class="navbar-collpase collpase" id="bs-example-navbar-collpase-1">
            <ul class="nav navbar-nav">
              <li class="<%=current_class?(root_path)%><%=current_class?(products_path)%>"><%= link_to t('navigation.products.list'), products_path %></li>
              <li class="<%=current_class?(new_product_path)%>"><%= link_to t('navigation.products.new'), new_product_path %></li>
              <li class="<%=current_class?(control_users_path)%>"><%= link_to t('navigation.users.list'), control_users_path %></li>
              <li class="<%=current_class?(new_control_user_path)%>"><%= link_to t('navigation.users.new'), new_control_user_path %></li>
              <li class="<%=current_class?(destroy_user_session_path)%>"><%= link_to t('navigation.logout'), destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, message| %>
            <div class="text-center alert alert-<%=key == 'notice' ? 'success' : 'danger' %>">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
          <%= render 'layouts/footer' %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="<%=controller_name%>">
  <head>
    <title><%=t(:system_name)%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body class="<%=controller_name%>">
    <div class="container text-center">
      <%= image_tag 'logo.png' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_with(model: product, local: true) do |form| %>
      <% if product.errors.any? %>
      <div class="alert alert-danger">
        <h5><%= t('errors_on_save') %></h5>
        <ul>
          <% product.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
            <% end %>
        </ul>
      </div>
      <% end %>

      <div class="form-row">
        <div class="form-group col-md-12">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control', placeholder: t('activerecord.attributes.product.name'), autofocus: true %>
        </div>
      </div>

      <div class="form-group">
				<div class="col-md-12">
          <div class="btn-group pull-right">
            <%= link_to t('back'), products_path, class: 'btn btn-default' %>
            <%= link_to 'Aumentar', product_add_quantity_path(product), class: 'btn btn-primary' if can_add_product_log?(product) %>
            <%= link_to 'Diminuir', product_remove_quantity_path(product), class: "btn btn-info" if can_remove_product_log?(product) %>
            <%= form.submit class: "btn btn-primary" %>
          </div>
				</div>
			</div>
    <% end %>
  </div>
</div>

app/views/products/_product_logs.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h3 class="text-center"><%= t('navigation.product_logs.title') %></h3>
    <table class="table mt-3 mb-3 datatable">
      <thead>
        <tr>
          <th>Usuário</th>
          <th>Ação</th>
          <th>Data e Hora</th>
        </tr>
      </thead>
    
      <tbody>
        <% product_logs.each do |product_log| %>
          <tr>
            <td><%= product_log.user.name %></td>
            <td><%= product_log.add? ? 'Aumentou' : 'Diminuiu' %></td>
            <td><%= l product_log.created_at, format: :long %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/edit.html.erb
<h3 class="text-center"><%= t('navigation.products.edit', amount: @product.amount) %></h3>

<%= render 'form', product: @product %>
<%= render 'product_logs', product_logs: @product.product_logs %>

app/views/products/index.html.erb
<h3 class="text-center"><%= t('navigation.products.title') %></h3>

<table class="table mt-3 mb-3 datatable">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Quantidade</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.amount %></td>
        <td>
          <div class='btn-group'>
            <%= link_to 'Aumentar', product_add_quantity_path(product), class: 'btn btn-sm btn-primary' if can_add_product_log?(product) %>
            <%= link_to 'Diminuir', product_remove_quantity_path(product), class: "btn btn-sm btn-info" if can_remove_product_log?(product) %>
            <%= link_to 'Exibir Detalhes e Log de Alterações', edit_product_path(product), class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Remover', product, method: :delete, data: { confirm: 'Tem certeza de realizar esta ação?' }, class: 'btn btn-sm btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h3 class="text-center"><%= t('navigation.products.new') %></h3>

<%= render 'form', product: @product %>